### ISSUE TITLE
About feature extractor

### ISSUE THREAD

**Issue by Legenhoor** [bytedance/RLFN#6]
How is the structure of a feature extractor ？  Is there just one  Conv k3s1-Tanh-Conv k3s1 ?

**Comment by fyan111** [comment]
Before Conv k3s1-Tanh-Conv k3s1， you need normalize input like VGG[ (input - mean) / std ]

**Comment by zhuzhu18** [comment]
what is the number of the input and output channel in Conv k3s1-Tanh-Conv k3s1?
